"""muriel.tools.diagrams.icons — curated Lucide glyphs for diagram steps.

``GLYPHS`` maps a slot name ("measure", "refresh", "database") to inner SVG
markup on a 24×24 grid, with no colour or stroke of its own: the generator
that places it wraps it in a ``<g>`` carrying brand-token stroke and weight.
:func:`resolve_icon` is the one entry point generators use; it accepts a slot
name, an alias from ``ALIASES``, or raw inner markup (anything containing
``<``) passed through unchanged.

The glyphs are generated by ``scripts/build_diagram_icons.py`` from a pinned
``lucide-static`` release (``LUCIDE_VERSION``).
"""

from __future__ import annotations

import difflib
from typing import Optional

from ._manifest import ALIASES, SLOTS
from .glyphs import GLYPHS, LUCIDE_VERSION

__all__ = ["GLYPHS", "LUCIDE_VERSION", "SLOTS", "ALIASES", "resolve_icon", "is_named"]


def is_named(icon: str) -> bool:
    """True when ``icon`` is a name to look up, not raw markup."""
    return "<" not in icon


def resolve_icon(icon: Optional[str]) -> Optional[str]:
    """Inner SVG markup for a slot name, alias, or raw markup.

    Raises ``ValueError`` for an unknown name, listing the closest slot or
    alias names so a typo ("refesh") is a one-step fix.
    """
    if icon is None:
        return None
    if not isinstance(icon, str):
        raise TypeError(f"icon must be a slot name or SVG markup; got {type(icon).__name__}")
    if not is_named(icon):
        return icon
    key = icon.strip().lower()
    key = ALIASES.get(key, key)
    if key in GLYPHS:
        return GLYPHS[key]
    known = sorted(set(GLYPHS) | set(ALIASES))
    close = difflib.get_close_matches(icon.strip().lower(), known, n=3, cutoff=0.6)
    hint = f" Did you mean {', '.join(repr(c) for c in close)}?" if close else ""
    raise ValueError(
        f"unknown icon {icon!r}.{hint} Known slots: {', '.join(GLYPHS)}. "
        f"Pass raw SVG inner markup for anything else."
    )
